Introduced options --version and --help; Improved parsing of FILE argument

diff --git a/src/make-aspkg b/src/make-aspkg
--- a/src/make-aspkg
+++ b/src/make-aspkg
@@ -1,10 +1,35 @@
 #!/bin/sh
+VERSION='1.0'
 
+## Parse optional arguments
+if [ "${1}" = "--version" ]; then
+    echo "$(basename "${0}") ${VERSION}"
+    exit 0
+elif [ "${1}" = "--help" ]; then
+    echo "Usage: $(basename "${0}") [OPTION] FILE"
+    echo ""
+    echo "Builds Debian package from Android Studio binary distribution"
+    echo ""
+    echo "Options:"
+    echo ""
+    echo "--help       Display this help message and exit"
+    echo "--version    Print version information and exit"
+    exit 0
+fi
+
+## Parse FILE argument
 if [ -z "${1}" ]; then
-    echo "Missing argument!"
+    echo "Error: Missing FILE argument!"
+    exit 1
+elif [ ! -e "${1}" ]; then
+    echo "Error: The file \"${1}\" does not exist!"
+    exit 1
+elif [ ! -r "${1}" ]; then
+    echo "Error: The file \"${1}\" is not readable!"
     exit 1
 fi
 
+## Try to use environment variable TMPDIR
 if [ -z "${TMPDIR}" ]; then
     TEMP_DIR="/tmp"
 else
@@ -14,7 +39,7 @@ fi
 PACKAGE_ROOT_DIR="${TEMP_DIR}/android-studio-package"
 PACKAGE_LIB_DIR="${PACKAGE_ROOT_DIR}/usr/lib"
 PACKAGE_AS_DIR="${PACKAGE_LIB_DIR}/android-studio"
-CURRENT_DIR=$(pwd)
+CURRENT_DIR="$(pwd)"
 
 ## Extract Android Studio in "lib" directory
 mkdir -p "${PACKAGE_LIB_DIR}"
@@ -49,7 +74,7 @@ fi
 sed -i "s/MAINTAINER_MAIL/${MAINTAINER_MAIL}/" ${PACKAGE_ROOT_DIR}/debian/control
 
 ## Extract version
-ANDROID_STUDIO_VERSION="$(basename ${1} | cut -d '-' -f 4)"
+ANDROID_STUDIO_VERSION="$(basename "${1}" | cut -d '-' -f 4)"
 
 ## Create changelog
 cd ${PACKAGE_ROOT_DIR}
